### ISSUE TITLE
どんなレイアウトがいいですか？

### ISSUE THREAD

**Issue by UDAZ** [LAPUTA-4/nagano_cake#64]
今日の夜、明日の朝までにいいなと思ったサイトやサイトの機能などをあげて、朝ディスカッションして方向性や実装する機能などを纏めたいと思います！(どんどんお願いします！)

**Comment by UDAZ** [comment]
[ゴディバ](https://www.godiva.co.jp/shop/)
・メニュー関連の機能がいいと思います。

**Comment by otinu** [comment]
https://bossathome.com/

トップ画面だけでもフルスクリーン(写真が画面いっぱいにbackground-imageで広がる)！

**Comment by otinu** [comment]
Google Fonts　などを活用して、ちょっとオシャレにするのもありですね！

**Comment by haraguchi12** [comment]
https://journey-leather.com
このサイトの商品画像の動きが綺麗なので提案として！

**Comment by haraguchi12** [comment]
https://sankoudesign.com/category/ec-onlineshop/
レイアウトの参考資料まとめサイトを共有しておきます！
このサイトの画像にカーソル合わせた時の動きも面白いかなと思いました。

**Comment by otinu** [comment]
> [ゴディバ](https://www.godiva.co.jp/shop/)
> ![image](https://user-images.githubusercontent.com/77953632/119222226-3ced3380-bb2e-11eb-966d-252405951b00.png)
> ・メニュー関連の機能がいいと思います。

**Comment by otinu** [comment]
> > [ゴディバ](https://www.godiva.co.jp/shop/)
> > ![image](https://user-images.githubusercontent.com/77953632/119222226-3ced3380-bb2e-11eb-966d-252405951b00.png)
> > ・メニュー関連の機能がいいと思います。

メニュー、ニュルニュル動きますね～w

**Comment by otinu** [comment]
> https://journey-leather.com
> このサイトの商品画像の動きが綺麗なので提案として！

トップのサイドバーが「 逆L字 」になってるところが初見で痺れましたb

**Comment by otinu** [comment]
すみません、間違えてクローズにしてました💦

**Comment by otinu** [comment]
> https://sankoudesign.com/category/ec-onlineshop/
> レイアウトの参考資料まとめサイトを共有しておきます！
> このサイトの画像にカーソル合わせた時の動きも面白いかなと思いました。

『SANKOU!』すごい見やすい!!　共有ありがとうございます～！
自分も下記を参考にしました！ ご参考までに。
https://www.thebestdesigns.com/

**Comment by otinu** [comment]
https://www.ghibli.jp/works/laputa/

例えば、メインテーマは「カフェ」としつつ、サブテーマで「ラピュタ」も絡めていきたいですね～w
公式も作品静止画を「※画像は常識の範囲でご自由にお使いください。」とのことなので、活用していきたいです！

**Comment by otinu** [comment]
https://www.ghibli.jp/works/laputa/#&gid=1&pid=38

「ご注文ありがとうございます」画面に、これ挿し込みたいな～w

**Comment by otinu** [comment]
https://ciatr.jp/topics/312308

このサイト見ると、「バルス == 閉じよ」って意味らしいです。
個人的に、宮崎監督がラピュタで意識したことを一言で表すと、「天地」とか「乖離」なのかなって思います。
天は管理者(目に見えない雲の向こう)、地はエンドユーザー(皆平等に踏みしめている)って隠しコンセプトとして、注文完了画面で「バルス == 空と大地が繋がる == 管理者とエンドユーザーがつながる == 皆が笑顔になる」ってアプリ全体でストーリーが組めるとアプリに深みが出そうですね！

**Comment by UDAZ** [comment]
ご注文ありがとうございました僕はこんな感じがいいです。SVG挑戦やってみたいです。
[参考](https://www.google.com/url?sa=i&url=https%3A%2F%2Fcodemyui.com%2Fthank-text-animation-using-svg%2F&psig=AOvVaw1e6vwCnXGhoycv9Gs4m1uS&ust=1621787734607000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNjlnqHc3fACFQAAAAAdAAAAABAD)
